import accordion from './parts/accordion';
import bottomSlider    from './parts/bottomSlider';
import calculator    from  './parts/calculator';
import hamburger    from  './parts/hamburger';
import loadingBlocks    from  './parts/loadingBlocks';
import mainSlider    from  './parts/mainSlider';
import mainForm    from  './parts/mainForm';
import modalWindows    from  './parts/modalWindows';
import scrollModal    from  './parts/scrollModal';
import pictures    from  './parts/pictures';
import tabs    from  './parts/tabs';

accordion();
bottomSlider();
calculator();
hamburger();
loadingBlocks();
mainSlider();
modalWindows();
mainForm();
scrollModal();
pictures();
tabs();